// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_JlEEcmOxggwnYPIguuCe6imsb3_yQE',
    appId: '1:814247894419:web:fb565f67692e4ca6559c66',
    messagingSenderId: '814247894419',
    projectId: 'snoringmind',
    authDomain: 'snoringmind.firebaseapp.com',
    databaseURL: 'https://snoringmind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snoringmind.firebasestorage.app',
    measurementId: 'G-94BGRZ026M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_cnN72b5mFTtGO7-uaZKuKKDMtr4D7nQ',
    appId: '1:814247894419:android:219e1e920b452ea5559c66',
    messagingSenderId: '814247894419',
    projectId: 'snoringmind',
    databaseURL: 'https://snoringmind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snoringmind.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-_JlEEcmOxggwnYPIguuCe6imsb3_yQE',
    appId: '1:814247894419:web:08294c7674540acf559c66',
    messagingSenderId: '814247894419',
    projectId: 'snoringmind',
    authDomain: 'snoringmind.firebaseapp.com',
    databaseURL: 'https://snoringmind-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'snoringmind.firebasestorage.app',
    measurementId: 'G-PWS1W4WRDC',
  );
}
